config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, 
  # see https://guides.rubyonrails.org/routing.html

  root    "home#top"

  # ログイン/ログアウト
  get     "/login"            => "sessions#new"
  post    "/login"            => "sessions#create"
  delete  "/logout"           => "sessions#destroy"

  get     "users/new"         => "users#new"
  post    "users/create"      => "users#create"
  delete  "users/:id/destroy" => "users#destroy"

  get     "tasks/index"       => "tasks#index"
  get     "tasks/new"         => "tasks#new"
  post    "tasks/create"      => "tasks#create"
  
  get     "tasks/:id/edit"    => "tasks#edit"
  patch   "tasks/:id/update"  => "tasks#update"
  delete  "tasks/:id/destroy" => "tasks#destroy"

  post    "tasks/:id/completed" =>  "tasks#completed"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :name,    presence: true, length: { maximum: 140}
  validates :scheduled_on, presence: true
  attribute :scheduled_on, :date, default: Date.today

  def user
    return User.find_by(id: self.user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy, foreign_key: :user_id
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: {maximum: 50} 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です。"
      redirect_to "/login"
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています。"
      redirect_to "/tasks/index"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :forbid_login_user, {only: [:new, :create]}
  
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "ログインしました。"
    else
      @error_txt = "入力に誤りがあるか、登録されていません。"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "ログアウトしました。"
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}
  
  def index
    @tasks = @current_user.tasks.all.order(scheduled_on: "ASC")
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(
      **task_params,
      user_id: @current_user.id)
    if @task.save
      flash[:notice] = "タスク作成！"
      redirect_to("/tasks/index")
    else
      render("tasks/new")
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    if @task.save
      flash[:notice] = "タスク編集完了！"
      redirect_to("/tasks/index")
    else
      render("tasks/edit")
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to("/tasks/index")
  end

  def completed
    @task = Task.find(params[:id])
    if @task.is_completed == false
      @task.update(is_completed: true, completed_on: Date.today)
    elsif @task.is_completed == true
      @task.update(is_completed: false, completed_on: nil)
    end

    redirect_to("/tasks/index")

  end

  private

    def task_params
      params.require(:task).permit(:name, :scheduled_on)
    end

    def ensure_correct_user
      @task = Task.find_by(id: params[:id])
      if @task.user_id != @current_user.id
        flash[:notice] = "権限がありません"
        redirect_to("/tasks/index")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :forbid_login_user, {only: [:new, :create]}
  before_action :authenticate_user, {only: [:destroy]}

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザー登録成功！"
      redirect_to "/"
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザー退会"
    redirect_to :root
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="container">
<h1>TODOはじめましょう</h1>
</div>
<%= flash[:notice] %>
<% if @current_user %>
  <div>
    <%= link_to("ログアウト", "/logout", {method: "delete"}) %>
    <%= link_to("タスク一覧", "/tasks/index") %>
    <%= link_to("退会","/users/#{@current_user.id}/destroy", {method: "delete"}) %>
    </div>
<% else %>
<div class="container">
  <div class="row">
    <div class="col-xl-12">
      <%= link_to("新規ユーザー登録","/users/new", class:"btn btn-primary btn-info mx-auto d-block") %>
    </div>
    <div class="col-xl-12">
      <%= link_to("ログイン","/login", class:"btn btn-primary btn-info mx-auto d-block") %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= form_with model: @task, url: "/tasks/#{@task.id}/update",local:true do |f| %>
<% if @task.errors.any? %>
<% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if @task.errors.include?(:name) %>
    <p style="color: red;"><%= @task.errors.full_messages_for(:name).first %>
    <% end %>
  </div>
  <div>
    <%= f.label :scheduled_on %>
    <%= f.date_field :scheduled_on %>
    <% if @task.errors.include?(:scheduled_on) %>
    <p style="color: red;"><%= @task.errors.full_messages_for(:scheduled_on).first %>
    <% end %>
  </div>
  <div><%= f.submit value="更新" %></div>
<% end %>

<%= link_to("一覧へ","/tasks/index") %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%= link_to("トップ","/") %>
<%= flash[:notice] %>
<%= link_to("新規タスク追加","/tasks/new") %>
<table>
<thead>
  <tr>
    <th>タスク名</th>
    <th>予定日</th>
  </tr>
</thead>
<tbody>
    <% @tasks.each do |task| %>
      <% if task.is_completed == false %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.scheduled_on %></td>
        <td><%= link_to("完了する？","/tasks/#{task.id}/completed",{method: "post"}) %></td>
        <td><%= link_to("編集","/tasks/#{task.id}/edit") %></td>
        <td><%= link_to("削除","/tasks/#{task.id}/destroy", method: "delete", data: {confirm: "本当に削除していい？"}) %></td>
      </tr>
      <% end %>
    <% end %>
</tbody>
</table>
<table>
<thead>
  <tr>
    <th>タスク名</th>
    <th>完了日</th>
  </tr>
</thead>
<tbody>
    <% @tasks.each do |task| %>
      <% if task.is_completed == true %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.completed_on %></td>
        <td><%= link_to("未完了に戻す？","/tasks/#{task.id}/completed",{method: "post"}) %></td>
        <td><%= link_to("削除","/tasks/#{task.id}/destroy", method: "delete", data: {confirm: "本当に削除していい？"}) %></td>
      </tr>
      <% end %>
    <% end %>
</tbody>
</table>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>
<%= form_with model: @task, url: tasks_create_path do |f| %>
<% if @task.errors.any? %>
<% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if @task.errors.include?(:name) %>
    <p style="color: red;"><%= @task.errors.full_messages_for(:name).first %>
    <% end %>
  </div>
  <div>
    <%= f.label :scheduled_on%>
    <%= f.date_field :scheduled_on %>
    <% if @task.errors.include?(:scheduled_on) %>
    <p style="color: red;"><%= @task.errors.full_messages_for(:scheduled_on).first %>
    <% end %>
  </div>
  <div><%= f.submit value="登録" %></div>
<% end %>

<%= link_to("一覧へ","/tasks/index") %>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>
<%= form_with model: @user, url: users_create_path do |f| %>
  <% if @user.errors.any? %>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: ["form-control","h-25","d-inline-block","w-50 p-3"] %>
    <% if @user.errors.include?(:name) %>
    <div class="alert alert-danger" role="alert"><%= @user.errors.full_messages_for(:name).first %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :email, class: ["col-sm-2", "col-form-label"] %>
    <%= f.text_field :email, class: ["form-control","form-control-sm"] , placeholder: "name@example.com" %>
    <% if @user.errors.include?(:email) %>
    <div class="alert alert-danger" role="alert"><%= @user.errors.full_messages_for(:email).first %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password %>
    <% if @user.errors.include?(:password) %>
    <div class="alert alert-danger" role="alert"><%= @user.errors.full_messages_for(:password).first %></div>
    <% end %>
    </div>
  </div>
  <div>
    <%= f.label :password_confirmation, "確認" %>
    <%= f.password_field :password_confirmation %>
    <% if @user.errors.include?(:password_confirmation) %>
      <div class="alert alert-danger" role="alert"><%= @user.errors.full_messages_for(:password_confirmation).first %><
    <% end %>
  </div>
  <div>
    <%= f.submit valuew="登録" %>
  </div>
<% end %>

<div>
<td><%= link_to("トップ","/") %></td>
</div>